version: "3.9"
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./Broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
  database:
    image: mysql_db
    ports:
      - 8888:8888
    restart: always
