version: "3.9"
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./Broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
  database:
    image: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solar_lab_db
    volumes:
      - ./Database/data:/var/lib/mysql
