version: "3.9"
services:
  broker:
    image: eclipse-mosquitto
    container_name: "SolarLab_Broker"
    ports:
      - 1883:1883
    volumes:
      - ./Broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
  database:
    image: mysql
    container_name: "SolarLab_Database"
    ports:
      - 3307:3306
    restart: always
    command: --local-infile=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solar_lab_db
    volumes:
      - ./Database/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50
  datawatcher:
    image: datawatcher
    container_name: "SolarLab_DataWatcher"
    restart: always
    volumes:
      - ../../../assistant/:/node/Data
    depends_on:
      database: 
        condition: service_healthy
