import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import React, { useEffect, useState } from 'react';

export default function Home() {
	return (
		<>
			<Head>
				<title>UPB Solar Remote Lab</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					<Head>
						<title>Create Next App</title>
						<meta name='description' content='Generated by create next app' />
						<link rel='icon' href='/upb.ico' />
						<meta
							name='viewport'
							content='initial-scale=1, width=device-width'
						/>
					</Head>

					<main className={styles.main}>
						<h1 className={styles.title}>
							Welcome to <a href='https://nextjs.org'>Next.js!</a>
						</h1>

						<p className={styles.description}>
							Get started by editing{' '}
							<code className={styles.code}>pages/index.js</code>
						</p>
					</main>
				</div>
			</main>
		</>
	);
}

