import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.scss';
import SignInDialog from '../components/SignInDialog';
import SignUpDialog from '../components/SignUpDialog';
import React, { useEffect, useState } from 'react';
import Button from '@mui/material/Button';

export default function Home() {
	const [openSignIn, setOpenSignIn] = useState(false);
	const [openSignup, setOpenSignUp] = useState(false);
	const handleOpenSignUpFromSignIn = () => {
		setOpenSignIn(false);
		setOpenSignUp(true);
	};
	const handleOpenSignInFromSignUp = () => {
		setOpenSignUp(false);
		setOpenSignIn(true);
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					<Head>
						<title>Create Next App</title>
						<meta name='description' content='Generated by create next app' />
						<link rel='icon' href='/favicon.ico' />
						<meta
							name='viewport'
							content='initial-scale=1, width=device-width'
						/>
					</Head>

					<main className={styles.main}>
						<h1 className={styles.title}>
							Welcome to <a href='https://nextjs.org'>Next.js!</a>
						</h1>

						<p className={styles.description}>
							Get started by editing{' '}
							<code className={styles.code}>pages/index.js</code>
						</p>

						<div style={{ textAlign: 'center' }}>
							<div style={{ display: 'inline-block' }}>
								<Button
									sx={{ mx: 2 }}
									onClick={() => setOpenSignIn(true)}
									variant='contained'
								>
									Iniciar Sesión
								</Button>
								<Button
									sx={{ mx: 2 }}
									onClick={() => setOpenSignUp(true)}
									variant='contained'
								>
									Registrarse
								</Button>
								<SignUpDialog
									open={openSignup}
									handleClose={() => setOpenSignUp(false)}
									onClickSignIn={handleOpenSignInFromSignUp}
								/>
								<SignInDialog
									open={openSignIn}
									handleClose={() => setOpenSignIn(false)}
									onClickSignup={handleOpenSignUpFromSignIn}
								/>
							</div>
						</div>
					</main>
				</div>
			</main>
		</>
	);
}

